name: Android CI

on:
  push:
    branches: [ mobile ]
#   pull_request:
#     branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x android/gradlew
    - name: Build and snyc web assets
      run : |
          export GT=${{ secrets.GT }} && sudo npm install -g npm
          export GT=${{ secrets.GT }} && npm install -f
          export GT=${{ secrets.GT }} && npm run build:mobile
    - name: Build with Gradle
      run: |
          cd android
          bash ./gradlew build
    - uses: r0adkll/sign-android-release@v1
      name: Sign app APK
      id: sign_app
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.ANDROID_SIGN_KEY_BASE64 }}
        alias: ${{ secrets.ANDROID_ALIAS }}
        keyStorePassword: ${{ secrets.ANDROID_KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
      env:
#         // override default build-tools version (29.0.3) -- optional
        BUILD_TOOLS_VERSION: "30.0.2"
        
    # Example use of `signedReleaseFile` output -- not needed
    - uses: actions/upload-artifact@v2
      with:
        name: Signed app bundle
        path: ${{steps.sign_app.outputs.signedReleaseFile}}
