name: Android CI

on:
  push:
    branches: [ mobile ]
#   pull_request:
#     branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x android/gradlew
    - name: Build and snyc web assets
      run : |
          export GT=${{ secrets.GT }} && npm install -g npm
          export GT=${{ secrets.GT }} && npm install -f
          export GT=${{ secrets.GT }} && npm run build:mobile
    - name: Build with Gradle
      run: ./android/gradlew build
