name: Node.js CI

on:
  push:
    branches:
      - master

jobs:
  buidWin:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build:desktop
      - run: cd electron && npm install && npm run build:win
        env:
          CI: true
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

  buildForLinux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: get-npm-version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@master
    - name: Install Snapcraft
      uses: samuelmeuli/action-snapcraft@v1
      with:
        snapcraft_token: ${{ secrets.SNAP_STORE_STABLE }}
        # skip_install: true # optional, if already installed in an earlier step
    - run: npm install
    - run: npm run build:desktop
    - run: npm run prepare:snap
    - run: npm run push:snap:stable
      env:
        CI: true
        PACKAGE_VERSION: ${{ steps.package-version.outputs.current-version}}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
