name: Node.js CI

on:
  push:
    branches:
      - master
      - electron

jobs:
  buidWin:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build:desktop
      - run: cd electron && npm install && npm run build:win
        env:
          CI: true
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build:desktop
    - run: cd electron && npm install && npm run build:snap
      env:
        CI: true
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
