name: Deploy Mac

on:
  push:
    branches: [ master ]
#  pull_request:
#    branches: [ master ]
env:
  GRT:  ${{ secrets.GITHUB_TOKEN }}
  GT:  ${{ secrets.GT }}
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install and build window package
        run: |
          npm install -g npm
          npm install -f
          npm run build:desktop
          cd desktop
          npm install -f
          npm run build:mac
          node upload.mac.js
