name: Deploy Website

on:
  push:
    branches: [ master ]
#  pull_request:
#    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: export GT=${{ secrets.GT }}
      - run: export FIREBASE_TOKEN=${{ secrets.FIREBASE_TOKEN }}
      - run: npm install -g firebase-tools
      - run: npm install
      - run: npm run deploy:web:ci
        env:
#           FIREBASE_TOKEN:  ${{ secrets.FIREBASE_TOKEN }}
          GRT:  ${{ secrets.GITHUB_TOKEN }}
