name: Deploy Desktop

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: get-npm-version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@master
    - name: Install Snapcraft
      uses: samuelmeuli/action-snapcraft@v1
      with:
        snapcraft_token: ${{ secrets.STORE_LOGIN }}
        skip_install: false
    - run: npm install
    #- run: echo $GT
    # - run: yarn install
    - run: npm run deploy:desktop:snap
      env:
        CI: true
        PACKAGE_VERSION: ${{ steps.package-version.outputs.current-version}}
        GT: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
