name: Deploy Win

on:
  push:
    branches: [ win ]
#  pull_request:
#    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: export GT=${{ secrets.GT }}
      - run: export FIREBASE_TOKEN=${{ secrets.FIREBASE_TOKEN }}
      - run: npm install -g npm
#      - run: npm install -g firebase-tools
      - run: export GT=${{ secrets.GT }} && npm install -f
      - run: export GT=${{ secrets.GT }} && npm run build:desktop
      - run: export GT=${{ secrets.GT }} && cd desktop && docker run --rm -e GT=${{ secrets.GT }} -v $PWD:/project electronuserland/builder:wine npm i -f && npm run build:win
        env:
          #           FIREBASE_TOKEN:  ${{ secrets.FIREBASE_TOKEN }}
          GRT:  ${{ secrets.GITHUB_TOKEN }}
