name: Build win app

on:
  push:
    branches:
      - win
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    env:
      GT: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
           npm install -g npm
           GT=${{ secrets.GITHUB_TOKEN }} npm install -f
           npm run build:desktop
           cd desktop
           GT=${{ secrets.GITHUB_TOKEN }} npm install
           docker run --rm -v $PWD:/desktop electronuserland/builder:wine bash "GT=${{ secrets.GITHUB_TOKEN }} npm install && npm run build:win"
           ls
