name: Deploy Win

on:
  push:
    branches: [ win ]
#  pull_request:
#    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: |
          npm install -g npm
          npm install -f
          npm run build:desktop
          cd desktop
          npm install -f
          npm run build:win
          ls dist
        shell: powershell
        env:
          GRT:  ${{ secrets.GITHUB_TOKEN }}
          GT:  ${{ secrets.GT }}
