name: Build win app

on:
  push:
    branches:
      - win
      - master

jobs:
  build:
    defaults:
      run:
        shell: powershell
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [14.x]
    env:
      GT: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
           $env:GT = "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"
           npm install -g npm
           npm install -f
           echo $GT
           npx ng build --configuration production -c=desktopProd --base-href=./
           cp -r dist/smartstock desktop
           node desktop-version.js
           cd desktop
           npm install
           npm run build:win
           npm install -g ipfs
           jsipfs init

           jsipfs add -r ./dist
