name: Build win app

on:
  push:
    branches:
      - win
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          npm-version: 7.x
          registry-url: https://npm.pkg.github.com
          scope: smartstocktz
          username: joshuamshana
          password: ${{ secrets.GT }}
      - run: |
           echo $GT
           npm install -f
           npm run build:desktop
           cd desktop
           npm install
           docker run --rm -v -e GT=$GT $PWD:/desktop electronuserland/builder:wine bash "npm install && npm run build:win"
           ls
    env:
      GT: ${{ secrets.GT }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
